import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/index.css";
import GraphQlProvider from "@/lib/Graphql/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <GraphQlProvider>
      <html lang="en">
        <body className={inter.className}>
          <main>{children}</main>
        </body>
      </html>
    </GraphQlProvider>
  );
}
